# This configures Dependabot to monitor the package, and open pull requests when dependencies update.
#
# For configuration format, see
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#directory

version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"

    # Do pip dependency checks every day
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:00"
      timezone: "Europe/Warsaw"

    # Ping owner directly for review
    assignees:
      - "Krystyna-Szybalska"

  # - package-ecosystem: "github-actions"
  #   # Workflow files stored in the default location of `.github/workflows`
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "friday"
  #     time: "16:00"
  #     timezone: "Europe/Warsaw"

  #   # Ping owner directly for review
  #   assignees:
  #     - "Krystyna-Szybalska"
