# Configuration for pre-commit hooks, see: https://pre-commit.com/
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
        # 1 MB - Don't commit notebooks with output!
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: detect-private-key
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.2.2"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.7.0
    hooks:
      - id: markdownlint-cli2
  # SEE: https://pre-commit.com/#repository-local-hooks
  # - repo: local
  #   hooks:
  #     - id: foo
  #       name: foo
  #       entry: foo
  #       language: system
  #       description: "Example local hook, see https://pre-commit.com/#repository-local-hooks"
